import { API_URL } from '../config/api.config';

export const ENDPOINTS = {
  auth: {
    login:   `${API_URL}/auth/login`,
    logout:  `${API_URL}/auth/logout`,
    refresh: `${API_URL}/auth/refresh`,
    me:      `${API_URL}/auth/me`,
  },
  projects: {
    list:          `${API_URL}/projects`,
    schedule:      `${API_URL}/projects/schedule`,
    allDocuments:  `${API_URL}/projects/documents`,
    detail:        (id: string) => `${API_URL}/projects/${id}`,
    steps:         (step: number) => `${API_URL}/projects/steps/${step}`,
    stepById:      (id: string, step: number) => `${API_URL}/projects/${id}/steps/${step}`,
    details:           (id: string) => `${API_URL}/projects/${id}/details`,
    budgetWizard:      (id: string) => `${API_URL}/projects/${id}/budget/wizard`,
    budget:            (id: string) => `${API_URL}/projects/${id}/budget`,
    budgetItem:        (id: string, bid: string) => `${API_URL}/projects/${id}/budget/${bid}`,
    monthlyWizard:     (id: string) => `${API_URL}/projects/${id}/monthly-wizard`,
    monthlyBulk:       (id: string, bid: string) => `${API_URL}/projects/${id}/budget/${bid}/monthly`,
    monthlySingle:     (id: string, bid: string, did: string) => `${API_URL}/projects/${id}/budget/${bid}/monthly/${did}`,
    monthlyGenerate:   (id: string, bid: string) => `${API_URL}/projects/${id}/budget/${bid}/monthly/generate`,
    invoices:          (id: string, bid: string) => `${API_URL}/projects/${id}/budget/${bid}/invoices`,
    componentsActs:    (id: string) => `${API_URL}/projects/${id}/technical-components/acts`,
    components:        (id: string) => `${API_URL}/projects/${id}/technical-components`,
    componentById:     (id: string, cid: string) => `${API_URL}/projects/${id}/technical-components/${cid}`,
    componentScopes:   (id: string, cid: string) => `${API_URL}/projects/${id}/technical-components/${cid}/activities`,
    scopeById:         (id: string, cid: string, sid: string) => `${API_URL}/projects/${id}/technical-components/${cid}/activities/${sid}`,
    budgetComponents:      (id: string) => `${API_URL}/projects/${id}/budget-components`,
    budgetComponentById:   (id: string, bid: string) => `${API_URL}/projects/${id}/budget-components/${bid}`,
    gantt:             (id: string) => `${API_URL}/projects/${id}/gantt`,
    snapshots:         (id: string) => `${API_URL}/projects/${id}/checkpoints`,
    scopeSnapshots:    (id: string, sid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints`,
    scopeSnapshot:     (id: string, sid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoint`,
    snapshotDelivery:  (id: string, sid: string, snid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/${snid}/delivery`,
    snapshotDeliveryVerifications: (id: string, sid: string, snid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/${snid}/delivery/verifications`,
    snapshotDeliveryVerificationById: (id: string, sid: string, snid: string, vid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/${snid}/delivery/verifications/${vid}`,
    risks:             (id: string) => `${API_URL}/projects/${id}/risks`,
    riskById:          (id: string, rid: string) => `${API_URL}/projects/${id}/risks/${rid}`,
    riskTracking:      (id: string, rid: string) => `${API_URL}/projects/${id}/risks/${rid}/tracking`,
    affiliates:        (id: string) => `${API_URL}/projects/${id}/affiliates`,
    affiliateById:     (id: string, aid: string) => `${API_URL}/projects/${id}/affiliates/${aid}`,
    indicators:                (id: string) => `${API_URL}/projects/${id}/indicators`,
    indicatorById:             (id: string, iid: string) => `${API_URL}/projects/${id}/indicators/${iid}`,
    indicatorVerifications:    (id: string, iid: string) => `${API_URL}/projects/${id}/indicators/${iid}/verifications`,
    indicatorVerificationById: (id: string, iid: string, vid: string) => `${API_URL}/projects/${id}/indicators/${iid}/verifications/${vid}`,
    documents:         (id: string) => `${API_URL}/projects/${id}/documents`,
    myAccess:          (id: string) => `${API_URL}/projects/${id}/my-access`,
    team:              (id: string) => `${API_URL}/projects/${id}/team`,
    teamMember:        (id: string, uid: string) => `${API_URL}/projects/${id}/team/${uid}`,
    teamMemberPermissions: (id: string, uid: string) => `${API_URL}/projects/${id}/team/${uid}/permissions`,
    extensions:        (id: string) => `${API_URL}/projects/${id}/extensions`,
    extensionById:     (id: string, eid: string) => `${API_URL}/projects/${id}/extensions/${eid}`,
  },
  contracts: {
    list:           `${API_URL}/contracts`,
    detail:         (id: string) => `${API_URL}/projects/${id}`,
    wizard:         (id: string) => `${API_URL}/projects/${id}/wizard`,
    step1:          `${API_URL}/projects/steps/1`,
    step1b:         (id: string) => `${API_URL}/projects/${id}/steps/supervisors`,
    stepById:       (id: string, step: number) => `${API_URL}/projects/${id}/steps/${step}`,
    step4:          (id: string, sid: string) => `${API_URL}/projects/${id}/steps/4/${sid}`,
    scopeVerify:    (id: string, scopeId: string) => `${API_URL}/projects/${id}/activities/${scopeId}/verifications`,
    scopeVerifyById:(id: string, scopeId: string, vid: string) => `${API_URL}/projects/${id}/activities/${scopeId}/verifications/${vid}`,
    locations:      (id: string) => `${API_URL}/projects/${id}/locations`,
    supports:       (id: string, sid: string) => `${API_URL}/projects/${id}/services/${sid}/supports`,
    supportById:    (id: string, sid: string, spid: string) => `${API_URL}/projects/${id}/services/${sid}/supports/${spid}`,
  },
  obligations: {
    list:           (id: string) => `${API_URL}/projects/${id}/obligations`,
    create:         (id: string) => `${API_URL}/projects/${id}/obligations`,
    byId:           (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}`,
    update:         (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}`,
    delete:         (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}`,
    evidences:      (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}/evidences`,
    evidenceUpload: (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}/evidences/upload`,
    evidenceById:   (id: string, oid: string, eid: string) => `${API_URL}/projects/${id}/obligations/${oid}/evidences/${eid}`,
    import:         (id: string) => `${API_URL}/projects/${id}/obligations/import`,
    replace:        (id: string) => `${API_URL}/projects/${id}/obligations/replace`,
  },
  supplyPlan: {
    list:    (id: string) => `${API_URL}/projects/${id}/supply-plan`,
    create:  (id: string) => `${API_URL}/projects/${id}/supply-plan`,
    byId:    (id: string, sid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}`,
    update:  (id: string, sid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}`,
    delete:  (id: string, sid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}`,
    summary: (id: string) => `${API_URL}/projects/${id}/supply-plan/summary`,
    import:  (id: string) => `${API_URL}/projects/${id}/supply-plan/import`,
  },
  tasks: {
    list:   `${API_URL}/tasks`,
    detail: (id: string) => `${API_URL}/tasks/${id}`,
  },
  users: {
    list:         `${API_URL}/users`,
    get:          (id: string) => `${API_URL}/users/${id}`,
    update:       (id: string) => `${API_URL}/users/${id}`,
    myAvatarUrl:  `${API_URL}/users/me/avatar-url`,
    avatarUrlById: (id: string) => `${API_URL}/users/${id}/avatar-url`,
  },
  templates: {
    download: (name: string) => `${API_URL}/templates/${name}`,
  },
  supervisors: {
    list:            `${API_URL}/projects/supervisors`,
    createUser:      `${API_URL}/users`,
    createAffiliate: (projectId: string) => `${API_URL}/projects/${projectId}/affiliates`,
  },
  divipola: {
    departamentos:       `${API_URL}/divipola/departamentos`,
    municipios:          (codDpto: string) => `${API_URL}/divipola/departamentos/${codDpto}/municipios`,
    veredas:             (codMpio: string) => `${API_URL}/divipola/municipios/${codMpio}/veredas`,
    createVereda:        `${API_URL}/divipola/veredas`,
    search:              `${API_URL}/divipola/search`,
  },
  fodcConfig: {
    list:        `${API_URL}/fodc-config`,
    totalMoney:  `${API_URL}/fodc-config/total_money`,
  },
  dashboard: {
    fodcProjects:     `${API_URL}/dashboard/fodc-projects`,
    budgetMonthly:    `${API_URL}/dashboard/budget/monthly`,
    allyCategories:   `${API_URL}/dashboard/allies/categories`,
    alliesList:       `${API_URL}/dashboard/allies/list`,
  },
};
