import { API_URL } from '../config/api.config';

export const ENDPOINTS = {
  auth: {
    login:   `${API_URL}/auth/login`,
    logout:  `${API_URL}/auth/logout`,
    refresh: `${API_URL}/auth/refresh`,
    me:      `${API_URL}/auth/me`,
    forgotPassword: `${API_URL}/auth/forgot-password`,
    resetPassword:  `${API_URL}/auth/reset-password`,
  },
  projects: {
    list:          `${API_URL}/projects`,
    schedule:      `${API_URL}/projects/schedule`,
    allDocuments:  `${API_URL}/projects/documents`,
    detail:        (id: string) => `${API_URL}/projects/${id}`,
    steps:         (step: number) => `${API_URL}/projects/steps/${step}`,
    stepById:      (id: string, step: number) => `${API_URL}/projects/${id}/steps/${step}`,
    details:           (id: string) => `${API_URL}/projects/${id}/details`,
    budgetWizard:      (id: string) => `${API_URL}/projects/${id}/budget/wizard`,
    budgetReconciliation: (id: string) => `${API_URL}/projects/${id}/budget/reconciliation`,
    budget:            (id: string) => `${API_URL}/projects/${id}/budget`,
    budgetItem:        (id: string, bid: string) => `${API_URL}/projects/${id}/budget/${bid}`,
    monthlyWizard:     (id: string) => `${API_URL}/projects/${id}/monthly-wizard`,
    monthlyBulk:       (id: string, bid: string) => `${API_URL}/projects/${id}/budget/${bid}/monthly`,
    monthlySingle:     (id: string, bid: string, did: string) => `${API_URL}/projects/${id}/budget/${bid}/monthly/${did}`,
    monthlyGenerate:   (id: string, bid: string) => `${API_URL}/projects/${id}/budget/${bid}/monthly/generate`,
    componentsActs:    (id: string) => `${API_URL}/projects/${id}/technical-components/acts`,
    components:        (id: string) => `${API_URL}/projects/${id}/technical-components`,
    componentById:     (id: string, cid: string) => `${API_URL}/projects/${id}/technical-components/${cid}`,
    componentOrder:    (id: string, cid: string) => `${API_URL}/projects/${id}/technical-components/${cid}/order`,
    componentScopes:   (id: string, cid: string) => `${API_URL}/projects/${id}/technical-components/${cid}/activities`,
    scopeById:         (id: string, cid: string, sid: string) => `${API_URL}/projects/${id}/technical-components/${cid}/activities/${sid}`,
    budgetComponents:      (id: string) => `${API_URL}/projects/${id}/budget-components`,
    budgetComponentById:   (id: string, bid: string) => `${API_URL}/projects/${id}/budget-components/${bid}`,
    gantt:             (id: string) => `${API_URL}/projects/${id}/gantt`,
    snapshots:         (id: string) => `${API_URL}/projects/${id}/checkpoints`,
    scopeSnapshots:    (id: string, sid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints`,
    scopeSnapshot:     (id: string, sid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoint`,
    scopeSnapshotsAutoGenerate: (id: string, sid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/auto-generate`,
    scopeSnapshotsDeleteRange: (id: string, sid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/delete-range`,
    scopeSnapshotById: (id: string, sid: string, snid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/${snid}`,
    scopeSnapshotsRebalance: (id: string, sid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/rebalance`,
    snapshotDelivery:  (id: string, sid: string, snid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/${snid}/delivery`,
    snapshotDeliveryVerifications: (id: string, sid: string, snid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/${snid}/delivery/verifications`,
    snapshotDeliveryVerificationById: (id: string, sid: string, snid: string, vid: string) => `${API_URL}/projects/${id}/activities/${sid}/checkpoints/${snid}/delivery/verifications/${vid}`,
    trackingReport:         (id: string) => `${API_URL}/projects/${id}/tracking-report`,
    trackingReportCsv:      (id: string) => `${API_URL}/projects/${id}/tracking-report/export.csv`,
    trackingReportTokens:   (id: string) => `${API_URL}/projects/${id}/tracking-report/tokens`,
    trackingReportTokenById:(id: string, tid: string) => `${API_URL}/projects/${id}/tracking-report/tokens/${tid}`,
    risks:             (id: string) => `${API_URL}/projects/${id}/risks`,
    evaluateRisk:      (id: string) => `${API_URL}/projects/${id}/risks/evaluate`,
    riskById:          (id: string, rid: string) => `${API_URL}/projects/${id}/risks/${rid}`,
    riskTracking:      (id: string, rid: string) => `${API_URL}/projects/${id}/risks/${rid}/tracking`,
    affiliates:        (id: string) => `${API_URL}/projects/${id}/affiliates`,
    affiliateById:     (id: string, aid: string) => `${API_URL}/projects/${id}/affiliates/${aid}`,
    affiliatesBulk:    (id: string) => `${API_URL}/projects/${id}/affiliates/bulk`,
    indicators:                (id: string) => `${API_URL}/projects/${id}/indicators`,
    indicatorById:             (id: string, iid: string) => `${API_URL}/projects/${id}/indicators/${iid}`,
    indicatorVerifications:    (id: string, iid: string) => `${API_URL}/projects/${id}/indicators/${iid}/verifications`,
    indicatorVerificationById: (id: string, iid: string, vid: string) => `${API_URL}/projects/${id}/indicators/${iid}/verifications/${vid}`,
    documents:         (id: string) => `${API_URL}/projects/${id}/documents`,
    myAccess:          (id: string) => `${API_URL}/projects/${id}/my-access`,
    team:              (id: string) => `${API_URL}/projects/${id}/team`,
    teamMember:        (id: string, uid: string) => `${API_URL}/projects/${id}/team/${uid}`,
    teamMemberPermissions: (id: string, uid: string) => `${API_URL}/projects/${id}/team/${uid}/permissions`,
    extensions:        (id: string) => `${API_URL}/projects/${id}/extensions`,
    extensionById:     (id: string, eid: string) => `${API_URL}/projects/${id}/extensions/${eid}`,
    disbursements:     (id: string) => `${API_URL}/projects/${id}/disbursements`,
    disbursementById:  (id: string, did: string) => `${API_URL}/projects/${id}/disbursements/${did}`,
    disbursementInvoices:    (id: string, did: string) => `${API_URL}/projects/${id}/disbursements/${did}/invoices`,
    disbursementInvoiceById: (id: string, did: string, iid: string) => `${API_URL}/projects/${id}/disbursements/${did}/invoices/${iid}`,
    disbursementReceipts:    (id: string, did: string, iid: string) => `${API_URL}/projects/${id}/disbursements/${did}/invoices/${iid}/receipts`,
    disbursementReceiptById: (id: string, did: string, iid: string, rid: string) => `${API_URL}/projects/${id}/disbursements/${did}/invoices/${iid}/receipts/${rid}`,
    disbursementReceiptDocument: (id: string, did: string, iid: string, rid: string) => `${API_URL}/projects/${id}/disbursements/${did}/invoices/${iid}/receipts/${rid}/document`,
    cashFlow:          (id: string) => `${API_URL}/projects/${id}/cash-flow`,
    executions:        (id: string) => `${API_URL}/projects/${id}/executions`,
    executionById:     (id: string, eid: string) => `${API_URL}/projects/${id}/executions/${eid}`,
    executionsMonthlySummary: (id: string) => `${API_URL}/projects/${id}/executions/summary`,
    hitos:             (id: string) => `${API_URL}/projects/${id}/hitos`,
    hitoById:          (id: string, hid: string) => `${API_URL}/projects/${id}/hitos/${hid}`,
    hitoComplete:      (id: string, hid: string) => `${API_URL}/projects/${id}/hitos/${hid}/complete`,
    hitoReopen:        (id: string, hid: string) => `${API_URL}/projects/${id}/hitos/${hid}/reopen`,
    budgetReport:      (id: string) => `${API_URL}/projects/${id}/reports/budget`,
    trackingReportDoc: (id: string) => `${API_URL}/projects/${id}/reports/tracking`,
    guarantees:        (id: string) => `${API_URL}/projects/${id}/guarantees`,
    guaranteeById:     (id: string, gid: string) => `${API_URL}/projects/${id}/guarantees/${gid}`,
    signature:         (id: string) => `${API_URL}/projects/${id}/signature`,
    signatureImage:    (id: string, kind: 'prepared' | 'approved') => `${API_URL}/projects/${id}/signature/${kind}/image`,
  },
  contracts: {
    list:           `${API_URL}/contracts`,
    detail:         (id: string) => `${API_URL}/projects/${id}`,
    wizard:         (id: string) => `${API_URL}/projects/${id}/wizard`,
    step1:          `${API_URL}/projects/steps/1`,
    step1b:         (id: string) => `${API_URL}/projects/${id}/steps/supervisors`,
    stepById:       (id: string, step: number) => `${API_URL}/projects/${id}/steps/${step}`,
    step4:          (id: string, sid: string) => `${API_URL}/projects/${id}/steps/4/${sid}`,
    scopeVerify:    (id: string, scopeId: string) => `${API_URL}/projects/${id}/activities/${scopeId}/verifications`,
    scopeVerifyById:(id: string, scopeId: string, vid: string) => `${API_URL}/projects/${id}/activities/${scopeId}/verifications/${vid}`,
    locations:      (id: string) => `${API_URL}/projects/${id}/locations`,
    supports:       (id: string, sid: string) => `${API_URL}/projects/${id}/services/${sid}/supports`,
    supportById:    (id: string, sid: string, spid: string) => `${API_URL}/projects/${id}/services/${sid}/supports/${spid}`,
    updateValue:    (id: string) => `${API_URL}/projects/${id}/value`,
  },
  obligations: {
    list:           (id: string) => `${API_URL}/projects/${id}/obligations`,
    create:         (id: string) => `${API_URL}/projects/${id}/obligations`,
    byId:           (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}`,
    update:         (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}`,
    delete:         (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}`,
    evidences:      (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}/evidences`,
    evidenceUpload: (id: string, oid: string) => `${API_URL}/projects/${id}/obligations/${oid}/evidences/upload`,
    evidenceById:   (id: string, oid: string, eid: string) => `${API_URL}/projects/${id}/obligations/${oid}/evidences/${eid}`,
    import:         (id: string) => `${API_URL}/projects/${id}/obligations/import`,
    replace:        (id: string) => `${API_URL}/projects/${id}/obligations/replace`,
  },
  supplyPlan: {
    list:    (id: string) => `${API_URL}/projects/${id}/supply-plan`,
    create:  (id: string) => `${API_URL}/projects/${id}/supply-plan`,
    byId:    (id: string, sid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}`,
    update:  (id: string, sid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}`,
    delete:  (id: string, sid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}`,
    summary: (id: string) => `${API_URL}/projects/${id}/supply-plan/summary`,
    import:  (id: string) => `${API_URL}/projects/${id}/supply-plan/import`,
    payments:          (id: string, sid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}/payments`,
    paymentById:       (id: string, sid: string, pid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}/payments/${pid}`,
    paymentInvoice:    (id: string, sid: string, pid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}/payments/${pid}/invoice`,
    paymentEvidence:   (id: string, sid: string, pid: string) => `${API_URL}/projects/${id}/supply-plan/${sid}/payments/${pid}/evidence`,
  },
  tasks: {
    list:   `${API_URL}/tasks`,
    detail: (id: string) => `${API_URL}/tasks/${id}`,
  },
  users: {
    list:         `${API_URL}/users`,
    me:           `${API_URL}/users/me`,
    get:          (id: string) => `${API_URL}/users/${id}`,
    update:       (id: string) => `${API_URL}/users/${id}`,
    updateMe:     `${API_URL}/users/me`,
    changeMyPassword: `${API_URL}/users/me/password`,
    myAvatarUrl:  `${API_URL}/users/me/avatar-url`,
    avatarUrlById: (id: string) => `${API_URL}/users/${id}/avatar-url`,
  },
  templates: {
    download: (name: string) => `${API_URL}/templates/${name}`,
  },
  supervisors: {
    list:                    `${API_URL}/projects/supervisors`,
    createCoordinador:       `${API_URL}/users/coordinadores`,
    createSupervisorAliado:  `${API_URL}/users/supervisores-aliados`,
    createApoyo:             `${API_URL}/users/apoyo`,
    createAffiliate: (projectId: string) => `${API_URL}/projects/${projectId}/affiliates`,
    update:      (id: string) => `${API_URL}/users/supervisores-aliados/${id}`,
    activate:    (id: string) => `${API_URL}/users/supervisores-aliados/${id}/activate`,
    deactivate:  (id: string) => `${API_URL}/users/supervisores-aliados/${id}`,
  },
  foundationUsers: {
    createDiligenciador: `${API_URL}/users/diligenciadores`,
    activate:   (id: string) => `${API_URL}/users/${id}/activate`,
    deactivate: (id: string) => `${API_URL}/users/${id}`,
  },
  apoyo: {
    list:       `${API_URL}/users`,
    create:     `${API_URL}/users/apoyo`,
    detail:     (id: string) => `${API_URL}/users/${id}`,
    update:     (id: string) => `${API_URL}/users/${id}`,
    activate:   (id: string) => `${API_URL}/users/${id}/activate`,
    deactivate: (id: string) => `${API_URL}/users/${id}`,
  },
  divipola: {
    departamentos:       `${API_URL}/divipola/departamentos`,
    municipios:          (codDpto: string) => `${API_URL}/divipola/departamentos/${codDpto}/municipios`,
    veredas:             (codMpio: string) => `${API_URL}/divipola/municipios/${codMpio}/veredas`,
    createVereda:        `${API_URL}/divipola/veredas`,
    search:              `${API_URL}/divipola/search`,
  },
  fodcConfig: {
    list:        `${API_URL}/fodc-config`,
    totalMoney:  `${API_URL}/fodc-config/total_money`,
  },
  budgetCatalog: {
    list:       `${API_URL}/budget-catalog`,
    create:     `${API_URL}/budget-catalog`,
    update:     (id: string) => `${API_URL}/budget-catalog/${id}`,
    deactivate: (id: string) => `${API_URL}/budget-catalog/${id}`,
  },
  pucAccounts: {
    list:       `${API_URL}/puc-accounts`,
    create:     `${API_URL}/puc-accounts`,
    update:     (id: string) => `${API_URL}/puc-accounts/${id}`,
    deactivate: (id: string) => `${API_URL}/puc-accounts/${id}`,
  },
  allies: {
    list:        `${API_URL}/allies`,
    create:      `${API_URL}/allies`,
    detail:      (id: string) => `${API_URL}/allies/${id}`,
    update:      (id: string) => `${API_URL}/allies/${id}`,
    deactivate:  (id: string) => `${API_URL}/allies/${id}`,
    activate:    (id: string) => `${API_URL}/allies/${id}/activate`,
    supervisors: (id: string) => `${API_URL}/allies/${id}/supervisors`,
  },
  dashboard: {
    fodcProjects:     `${API_URL}/dashboard/fodc-projects`,
    budgetMonthly:    `${API_URL}/dashboard/budget/monthly`,
    allyCategories:   `${API_URL}/dashboard/allies/categories`,
    alliesList:       `${API_URL}/dashboard/allies/list`,
  },
};
